import type { Metadata } from "next";
import { Inter, Russo_One, Handlee, Kaushan_Script } from "next/font/google";
import "./globals.css";

const inter = Russo_One({ weight: "400", style: "normal", display: "swap", subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={inter.className}>{children}</body>
        </html>
    );
}
